
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/securitydb
    #    url: jdbc:h2:mem:schoolDb
    username: lijy1
    password: xsw2!QAZ
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defautPageSize: 10

#第二个数据库
school:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/schooldb
    username: lijy1
    password: xsw2!QAZ

#    database-platform: org.hibernate.dialect.H2Dialect
jwt:
  secret: thisisthesecretkey
custom:
  config:
    sign:
      method: nojwt
server:
  port: 8080
