spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/securitydb
#    url: jdbc:h2:mem:schoolDb
    username: root
    password: 123456
  jpa:
    hibernate.hbm2ddl.auto: update
    open-in-view: false

#第二个数据库
school:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/schooldb
    username: root
    password: 123456

#    database-platform: org.hibernate.dialect.H2Dialect

